---
extends: default
rules:
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 80
    allow-non-breakable-inline-mappings: true
    allow-non-breakable-words: true
