---
name: Go Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

env:
  GO111MODULE: true

permissions:
  contents: read

jobs:
  golangci-lint:
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: read # for golangci/golangci-lint-action to fetch PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.20"
          check-latest: true
          cache: true

      - uses: golangci/golangci-lint-action@v3.6.0
        with:
          version: latest
          args: --verbose

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          pre-commit --version
          pre-commit run --from-ref origin/main --to-ref HEAD

  build:
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.20"
          cache: true

      - name: Go Build
        run: make build

      - name: Go Test
        run: make test
